### ISSUE TITLE
Opdracht 11 - Issue op jQuery

### ISSUE THREAD

**Issue by ghost** [Thomaach/MI2#1]
Maak in html een lijstje van drie favoriete maaltijden.
Als je op de maaltijd klikt dan slide er een lijstje van de ingrediënten uit.

Plaats onder het lijstje van de maaltijden ook drie foto's van elke maaltijd. Als je op de foto van de maaltijd klikt dan slide het lijstje van de ingredienten ook open.

Door terug op de lijst item/foto te klikken zal het ook weer sluiten.
-------------------------------------------------------------------------------------------------------------------
@Thomaach

**Comment by Thomaach** [comment]
Kijk eens naar de map issue.
